### ISSUE TITLE
Tests missing syntax validation, lint, etc

### ISSUE THREAD

**Issue by locknut** [saltedsignal/puppet-certmonger#15]
I'm a bit concerned that #12 didn't get picked up by the tests. How can get travis to automatically validate and lint commits and PRs?

@JAORMX any ideas?

**Comment by JAORMX** [comment]
@locknut good question. It's been a long time since I first introduced those. Unfortunately I'm not sure why :/

**Comment by locknut** [comment]
Can we tweak the .travis-ci.yml file to run the rake validate/lint tasks?

http://razorconsulting.com.au/setting-up-puppet-module-testing-from-scratch-part-i-puppet-syntax-puppet-lint-and-rspec-puppet.html
