### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ekohl** [saltedsignal/puppet-certmonger#22]
Is this module still maintained? The last release is quite old and I'm hesitant to start using this module.

If not, would it be an idea to transfer to [Voxpupuli](https://voxpupuli.org/)?

**Comment by JAORMX** [comment]
Well, at least I haven't had any need to add new features to it. We've been consistently using the certmonger_certificate provider in OpenStack for a couple of years now and don't plan to move away from it any time soon.

**Comment by JAORMX** [comment]
@ekohl transferring it to Voxpupuli is fine by me. I think this was brought up before. At least on my side this is acceptable.

**Comment by ekohl** [comment]
https://github.com/saltedsignal/puppet-certmonger/pull/23 at least updates it so it's usable in current Puppet versions. It would be great if the version on the forge was updated.

However, I'm also fine with helping to transfer it to Voxpupuli.

**Comment by locknut** [comment]
Apologies for the delay, yes, this module is still maintained.
