### ISSUE TITLE
Ask for a new tag/release for puppet-certmonger

### ISSUE THREAD

**Issue by raildo** [saltedsignal/puppet-certmonger#29]
We did some improvements on puppet-certmonger and it has been a while that we don't have a release for this repository.

Would be nice to have a new tag and release created for it.

**Comment by locknut** [comment]
@JAORMX I think we might have accidentally created a v2.4.0 tag in github that doesn't align with the existing version 2.4.0 as published in the forge. Can we fix the v2.4.0 tag in github to point to the same version in the forge? Then we can release 2.5.0 and I'll publish to forge?

**Comment by JAORMX** [comment]
@locknut oh! I didn't know we had another v2.4.0 release in forge. What's it pointing to? Or, could you fix the tag there?

**Comment by raildo** [comment]
@locknut I created the v2.5.0 release on https://github.com/saltedsignal/puppet-certmonger/releases let me know if everything is ok and we can close this issue.

**Comment by locknut** [comment]
@raildo thanks for that, can we version bump metadata.json as well?
