### ISSUE TITLE
Support for storing CA certs

### ISSUE THREAD

**Issue by pioto** [saltedsignal/puppet-certmonger#5]
It'd be helpful to have an additional `cacertfile` parameter, which would be passed to `ipa-getcert request` with the `-F` flag.

**Comment by locknut** [comment]
Yes, that would be useful. It would be even more useful if `ipa-getcert request -F /path/to/issuing.ca.pem` actually worked as described in the documentation. It's supposed to write out the certificate of the **issuing** CA. From what I can see, it doesn't actually do this for IPA sub CAs =\

**Comment by locknut** [comment]
This should now be implemented with https://github.com/saltedsignal/puppet-certmonger/commit/73cd5da39e4b3c48a408f8060008b4457e8d86ca
@pioto  Let me know how you go.

**Comment by locknut** [comment]
@pioto have you had a chance to try out the new `cacertfile` parameter? Keen to get it into the next release...

**Comment by pioto** [comment]
Hi,

I haven't had a chance to try this out; actually, I've found that it's easier to just reconfigure my software to point to the default FreeIPA cert in `/etc/ipa/ca.crt`, because I have fewer issues with SELinux that way...

But, the patch looks like it should work, and since it's a new feature, I can't see how it would harm to just :shipit: ?
