### ISSUE TITLE
Using Puppet 4 types?

### ISSUE THREAD

**Issue by ekohl** [saltedsignal/puppet-certmonger#7]
Before I submit a PR I'm interested in what you think about using Puppet 4 types. Puppet 3 is EOL and ```validate_string``` and ```validate_absolute_path``` generate deprecation warnings. Replacing that with Puppet 4 types is easy but if you'll reject them there's no point in submitting a PR :)

**Comment by locknut** [comment]
Yeah +1 from me. I'm still wrapping my head around puppet 4 types and would be happy to accept help in getting rid of the deprecation warnings.

**Comment by JAORMX** [comment]
@ekohl that would be great! I could review that.
