### ISSUE TITLE
getcert location on Debian

### ISSUE THREAD

**Issue by lslng** [saltedsignal/puppet-certmonger#8]
Hi,

using the module on Debian GNU/Linux 9.1 (stretch), with native type/provider

on Debian, getcert is located in: /usr/bin/getcert
on CentOS, found it in /bin/getcert and in /usr/bin/getcert (hardlink)

I modified /etc/puppetlabs/code/environments/production/modules/certmonger/lib/puppet/provider/certmonger_certificate/certmonger_certificate.rb to correct the path.

Working perfectly after the modification

**Comment by JAORMX** [comment]
@lslng thanks for pointing this out, I'll look into it.

**Comment by JAORMX** [comment]
@lslng I just tried it out in CentOS and the new path works there too. thanks!

**Comment by locknut** [comment]
@lslng thanks for reporting the issue! Let us know if #9 hasn't fix it for you.
